name = "rrkishadi"
compatibility_date = "2026-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "rrkishadi-rsvp"
database_id = "488674d8-3f79-475d-9cef-ce27c65d6562"
